//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5.FindNearestStoreService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FindNearestStoreService.INearestStoreService")]
    public interface INearestStoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INearestStoreService/findNearestStore", ReplyAction="http://tempuri.org/INearestStoreService/findNearestStoreResponse")]
        string[] findNearestStore(string zipcode, string storeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INearestStoreService/findNearestStore", ReplyAction="http://tempuri.org/INearestStoreService/findNearestStoreResponse")]
        System.Threading.Tasks.Task<string[]> findNearestStoreAsync(string zipcode, string storeName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INearestStoreServiceChannel : Assignment5.FindNearestStoreService.INearestStoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NearestStoreServiceClient : System.ServiceModel.ClientBase<Assignment5.FindNearestStoreService.INearestStoreService>, Assignment5.FindNearestStoreService.INearestStoreService {
        
        public NearestStoreServiceClient() {
        }
        
        public NearestStoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NearestStoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NearestStoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NearestStoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] findNearestStore(string zipcode, string storeName) {
            return base.Channel.findNearestStore(zipcode, storeName);
        }
        
        public System.Threading.Tasks.Task<string[]> findNearestStoreAsync(string zipcode, string storeName) {
            return base.Channel.findNearestStoreAsync(zipcode, storeName);
        }
    }
}
