//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5.GasStationsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GasStationsService.IGasStationsService")]
    public interface IGasStationsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasStationsService/GetGasStationsData", ReplyAction="http://tempuri.org/IGasStationsService/GetGasStationsDataResponse")]
        string[][] GetGasStationsData(string city, string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGasStationsService/GetGasStationsData", ReplyAction="http://tempuri.org/IGasStationsService/GetGasStationsDataResponse")]
        System.Threading.Tasks.Task<string[][]> GetGasStationsDataAsync(string city, string state);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGasStationsServiceChannel : Assignment5.GasStationsService.IGasStationsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GasStationsServiceClient : System.ServiceModel.ClientBase<Assignment5.GasStationsService.IGasStationsService>, Assignment5.GasStationsService.IGasStationsService {
        
        public GasStationsServiceClient() {
        }
        
        public GasStationsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GasStationsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GasStationsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GasStationsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[][] GetGasStationsData(string city, string state) {
            return base.Channel.GetGasStationsData(city, state);
        }
        
        public System.Threading.Tasks.Task<string[][]> GetGasStationsDataAsync(string city, string state) {
            return base.Channel.GetGasStationsDataAsync(city, state);
        }
    }
}
